// resources/js/react/pages/Checkout.tsx
import { Button } from '@/components/ui/button';
import { Field, FieldLabel } from '@/components/ui/field';
import { Input } from '@/components/ui/input';
import { useT } from '@/i18n';
import { useForm, usePage } from '@inertiajs/react';
import type { CheckoutSession } from '@modules/billing/resources/js/types';
import { useState, type FormEvent } from 'react';
import { getIntervalDisplay } from '../../lib/intervals';
import CheckoutLayout from '../layouts/CheckoutLayout';

import IconCheck from '~icons/heroicons/check';
import IconLock from '~icons/heroicons/lock-closed';

function formatPrice(amount: number, currency?: string): string {
    return new Intl.NumberFormat(undefined, {
        style: 'currency',
        currency: currency?.toUpperCase() ?? 'EUR',
    }).format(amount / 100);
}

export default function Checkout({
    session,
    handoffFailed = false,
}: {
    session: CheckoutSession;
    /** The provider could not be reached; trying again resends this same checkout. */
    handoffFailed?: boolean;
}) {
    const t = useT();
    const page = usePage();
    const user = page.props.auth?.user;

    const price = session.price;
    const product = price.product;

    const { data, setData, post, processing } = useForm({
        email: user?.email ?? '',
        coupon: '',
    });

    const [showCoupon, setShowCoupon] = useState(false);

    const retry = useForm({});

    function handleCheckout(event: FormEvent) {
        event.preventDefault();
        post(route('billing.checkout.store', session.uuid));
    }

    const summary = (
        <div data-testid="order-summary">
            <p className="text-foreground/70 text-sm">
                {t('Subscribe to :plan', { plan: product.name })}
            </p>

            <div className="mt-2 flex items-baseline gap-2">
                <span
                    data-testid="checkout-total"
                    className="text-foreground text-4xl font-semibold tracking-tight"
                >
                    {formatPrice(price.amount, price.currency)}
                </span>
                <span className="text-foreground/70 text-sm">
                    {getIntervalDisplay(price.interval)}
                </span>
            </div>

            {/* Line item */}
            <div className="border-border mt-8 border-t pt-6">
                <div className="flex items-start justify-between gap-4">
                    <div>
                        <h2
                            data-testid="checkout-product-name"
                            className="text-foreground font-medium"
                        >
                            {product.name}
                        </h2>
                        {product.description && (
                            <p
                                className="text-foreground/70 mt-1 text-sm"
                                dangerouslySetInnerHTML={{
                                    __html: product.description,
                                }}
                            />
                        )}
                    </div>
                    <span className="text-foreground shrink-0 text-sm">
                        {formatPrice(price.amount, price.currency)}
                    </span>
                </div>

                {!!product.features?.length && (
                    <ul className="mt-4 space-y-2">
                        {product.features.map((feature, index) => (
                            <li
                                key={index}
                                className="text-foreground/70 flex items-center gap-2 text-sm"
                            >
                                <IconCheck className="text-primary size-4 shrink-0" />
                                {feature}
                            </li>
                        ))}
                    </ul>
                )}
            </div>

            {/* Totals */}
            <div className="border-border mt-6 space-y-2 border-t pt-6">
                <div className="text-foreground/70 flex items-center justify-between text-sm">
                    <span>{t('Subtotal')}</span>
                    <span>{formatPrice(price.amount, price.currency)}</span>
                </div>
                <p className="text-foreground/50 text-xs">
                    {t('Tax will be calculated at payment if applicable')}
                </p>

                {/* Hidden until asked for, so it does not send anyone off
                    hunting for a code they do not have. */}
                {!showCoupon ? (
                    <button
                        type="button"
                        data-testid="checkout-coupon-toggle"
                        className="bg-foreground/5 text-foreground hover:bg-foreground/10 mt-2 rounded-lg px-3 py-2 text-sm font-medium transition"
                        onClick={() => setShowCoupon(true)}
                    >
                        {t('Add promotion code')}
                    </button>
                ) : (
                    <Field>
                        <FieldLabel htmlFor="coupon">
                            {t('Promotion code')}
                        </FieldLabel>
                        <Input
                            id="coupon"
                            name="coupon"
                            data-testid="checkout-coupon"
                            type="text"
                            placeholder={t('Enter your code')}
                            value={data.coupon}
                            onChange={(event) =>
                                setData('coupon', event.target.value)
                            }
                        />
                    </Field>
                )}
            </div>

            <div className="border-border mt-4 flex items-center justify-between border-t pt-4">
                <span className="text-foreground font-semibold">
                    {t('Total due today')}
                </span>
                <span className="text-foreground text-lg font-bold">
                    {formatPrice(price.amount, price.currency)}
                </span>
            </div>

            {!price.interval && (
                <p className="text-foreground/50 mt-3 text-xs">
                    {t(
                        'This is a one-time payment. You will not be charged again.',
                    )}
                </p>
            )}
        </div>
    );

    return (
        <CheckoutLayout
            title={t('Checkout')}
            backHref={route('billing.plans')}
            summary={summary}
        >
            {/* Right: the hand-off failed, or what we need from you */}
            {handoffFailed ? (
                <div
                    data-testid="checkout-handoff-failed"
                    className="space-y-4"
                >
                    <h2 className="text-foreground text-lg font-semibold">
                        {t('We could not reach the payment provider')}
                    </h2>
                    <p className="text-foreground/70 text-sm">
                        {t(
                            'Nothing has been charged. Try again in a moment; your checkout is kept.',
                        )}
                    </p>
                    <Button
                        data-testid="checkout-retry"
                        className="w-full text-base"
                        disabled={retry.processing}
                        onClick={() =>
                            retry.post(
                                route('billing.checkout.retry', session.uuid),
                            )
                        }
                    >
                        {retry.processing
                            ? t('Redirecting...')
                            : t('Try again')}
                    </Button>
                </div>
            ) : (
                <>
                    <h2 className="text-foreground text-lg font-semibold">
                        {t('Billing information')}
                    </h2>

                    <form
                        data-testid="checkout-form"
                        onSubmit={handleCheckout}
                        className="mt-6 space-y-4"
                    >
                        <Field>
                            <FieldLabel htmlFor="email">
                                {t('Email')}
                            </FieldLabel>
                            <Input
                                id="email"
                                name="email"
                                data-testid="checkout-email"
                                type="email"
                                placeholder={t('Enter your email')}
                                autoComplete="email"
                                required
                                value={data.email}
                                onChange={(event) =>
                                    setData('email', event.target.value)
                                }
                            />
                        </Field>

                        <p className="text-foreground/50 text-xs">
                            {t(
                                'Your billing address is collected on the payment page when it is needed.',
                            )}
                        </p>

                        <Button
                            type="submit"
                            data-testid="checkout-submit"
                            className="mt-6 w-full text-base"
                            disabled={processing}
                        >
                            {processing
                                ? t('Redirecting...')
                                : t('Proceed to Payment')}
                        </Button>

                        <div className="text-foreground/50 flex items-center justify-center gap-1.5 text-xs">
                            <IconLock className="size-3.5" />
                            {t('Payments are secure and encrypted')}
                        </div>

                        {/* Guarded: both routes belong to the host app, and a site without
                    them would otherwise take the whole checkout page down. */}
                        {route().has('terms') && route().has('privacy') && (
                            <p className="text-foreground/50 text-center text-xs">
                                {t('By continuing you agree to our')}{' '}
                                <a
                                    href={route('terms')}
                                    className="hover:text-foreground underline underline-offset-4"
                                >
                                    {t('Terms of Service')}
                                </a>{' '}
                                {t('and')}{' '}
                                <a
                                    href={route('privacy')}
                                    className="hover:text-foreground underline underline-offset-4"
                                >
                                    {t('Privacy Policy')}
                                </a>
                            </p>
                        )}
                    </form>
                </>
            )}
        </CheckoutLayout>
    );
}

// resources/js/vue/pages/Checkout.vue
<script setup lang="ts">
import { Button } from '@/components/ui/button';
import InputField from '@/components/ui/input/InputField.vue';
import { useForm, usePage } from '@inertiajs/vue3';
import type { CheckoutSession } from '@modules/billing/resources/js/types';
import { computed, ref } from 'vue';
import CheckoutLayout from '../layouts/CheckoutLayout.vue';
import { getIntervalDisplay } from '../../lib/intervals';

import IconCheck from '~icons/heroicons/check';
import IconLock from '~icons/heroicons/lock-closed';

const props = defineProps<{
    session: CheckoutSession;
    /** The provider could not be reached; trying again resends this same checkout. */
    handoffFailed?: boolean;
}>();

const page = usePage();
const user = computed(() => page.props.auth?.user);

const price = computed(() => props.session.price);
const product = computed(() => price.value.product);

const form = useForm({
    email: user.value?.email ?? '',
    coupon: '',
});

const showCoupon = ref(false);

function formatPrice(amount: number, currency?: string): string {
    return new Intl.NumberFormat(undefined, {
        style: 'currency',
        currency: currency?.toUpperCase() ?? 'EUR',
    }).format(amount / 100);
}

function handleCheckout() {
    form.post(route('billing.checkout.store', props.session.uuid));
}

const retry = useForm({});

function handleRetry() {
    retry.post(route('billing.checkout.retry', props.session.uuid));
}
</script>

<template>
    <CheckoutLayout :title="$t('Checkout')" :back-href="route('billing.plans')">
        <!-- Left: what is being bought -->
        <template #summary>
            <div data-testid="order-summary">
                <p class="text-foreground/70 text-sm">
                    {{ $t('Subscribe to :plan', { plan: product.name }) }}
                </p>

                <div class="mt-2 flex items-baseline gap-2">
                    <span
                        data-testid="checkout-total"
                        class="text-foreground text-4xl font-semibold tracking-tight"
                    >
                        {{ formatPrice(price.amount, price.currency) }}
                    </span>
                    <span class="text-foreground/70 text-sm">
                        {{ getIntervalDisplay(price.interval) }}
                    </span>
                </div>

                <!-- Line item -->
                <div class="border-border mt-8 border-t pt-6">
                    <div class="flex items-start justify-between gap-4">
                        <div>
                            <h2
                                data-testid="checkout-product-name"
                                class="text-foreground font-medium"
                            >
                                {{ product.name }}
                            </h2>
                            <p
                                v-if="product.description"
                                class="text-foreground/70 mt-1 text-sm"
                                v-html="product.description"
                            />
                        </div>
                        <span class="text-foreground shrink-0 text-sm">
                            {{ formatPrice(price.amount, price.currency) }}
                        </span>
                    </div>

                    <ul v-if="product.features?.length" class="mt-4 space-y-2">
                        <li
                            v-for="(feature, index) in product.features"
                            :key="index"
                            class="text-foreground/70 flex items-center gap-2 text-sm"
                        >
                            <IconCheck class="text-primary size-4 shrink-0" />
                            {{ feature }}
                        </li>
                    </ul>
                </div>

                <!-- Totals -->
                <div class="border-border mt-6 space-y-2 border-t pt-6">
                    <div
                        class="text-foreground/70 flex items-center justify-between text-sm"
                    >
                        <span>{{ $t('Subtotal') }}</span>
                        <span>{{
                            formatPrice(price.amount, price.currency)
                        }}</span>
                    </div>
                    <p class="text-foreground/50 text-xs">
                        {{
                            $t(
                                'Tax will be calculated at payment if applicable',
                            )
                        }}
                    </p>

                    <!-- Hidden until asked for, so it does not send anyone off
                         hunting for a code they do not have. -->
                    <button
                        v-if="!showCoupon"
                        type="button"
                        data-testid="checkout-coupon-toggle"
                        class="bg-foreground/5 text-foreground hover:bg-foreground/10 mt-2 rounded-lg px-3 py-2 text-sm font-medium transition"
                        @click="showCoupon = true"
                    >
                        {{ $t('Add promotion code') }}
                    </button>

                    <InputField
                        v-else
                        name="coupon"
                        data-testid="checkout-coupon"
                        type="text"
                        :label="$t('Promotion code')"
                        :placeholder="$t('Enter your code')"
                        v-model="form.coupon"
                    />
                </div>

                <div
                    class="border-border mt-4 flex items-center justify-between border-t pt-4"
                >
                    <span class="text-foreground font-semibold">
                        {{ $t('Total due today') }}
                    </span>
                    <span class="text-foreground text-lg font-bold">
                        {{ formatPrice(price.amount, price.currency) }}
                    </span>
                </div>

                <p
                    v-if="!price.interval"
                    class="text-foreground/50 mt-3 text-xs"
                >
                    {{
                        $t(
                            'This is a one-time payment. You will not be charged again.',
                        )
                    }}
                </p>
            </div>
        </template>

        <!-- Right: the hand-off failed, or what we need from you -->
        <div
            v-if="handoffFailed"
            data-testid="checkout-handoff-failed"
            class="space-y-4"
        >
            <h2 class="text-foreground text-lg font-semibold">
                {{ $t('We could not reach the payment provider') }}
            </h2>
            <p class="text-foreground/70 text-sm">
                {{
                    $t(
                        'Nothing has been charged. Try again in a moment; your checkout is kept.',
                    )
                }}
            </p>
            <Button
                data-testid="checkout-retry"
                class="w-full text-base"
                :disabled="retry.processing"
                @click="handleRetry"
            >
                {{ retry.processing ? $t('Redirecting...') : $t('Try again') }}
            </Button>
        </div>

        <template v-else>
            <h2 class="text-foreground text-lg font-semibold">
                {{ $t('Billing information') }}
            </h2>

            <form
                data-testid="checkout-form"
                @submit.prevent="handleCheckout"
                class="mt-6 space-y-4"
            >
                <InputField
                    name="email"
                    data-testid="checkout-email"
                    type="email"
                    :label="$t('Email')"
                    :placeholder="$t('Enter your email')"
                    autocomplete="email"
                    required
                    v-model="form.email"
                />

                <p class="text-foreground/50 text-xs">
                    {{
                        $t(
                            'Your billing address is collected on the payment page when it is needed.',
                        )
                    }}
                </p>

                <Button
                    type="submit"
                    data-testid="checkout-submit"
                    class="mt-6 w-full text-base"
                    :disabled="form.processing"
                >
                    {{
                        form.processing
                            ? $t('Redirecting...')
                            : $t('Proceed to Payment')
                    }}
                </Button>

                <div
                    class="text-foreground/50 flex items-center justify-center gap-1.5 text-xs"
                >
                    <IconLock class="size-3.5" />
                    {{ $t('Payments are secure and encrypted') }}
                </div>

                <!-- Guarded: both routes belong to the host app, and a site without
                 them would otherwise take the whole checkout page down. -->
                <p
                    v-if="route().has('terms') && route().has('privacy')"
                    class="text-foreground/50 text-center text-xs"
                >
                    {{ $t('By continuing you agree to our') }}
                    <a
                        :href="route('terms')"
                        class="hover:text-foreground underline underline-offset-4"
                    >
                        {{ $t('Terms of Service') }}
                    </a>
                    {{ $t('and') }}
                    <a
                        :href="route('privacy')"
                        class="hover:text-foreground underline underline-offset-4"
                    >
                        {{ $t('Privacy Policy') }}
                    </a>
                </p>
            </form>
        </template>
    </CheckoutLayout>
</template>
